name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
      - name: Create fresh android files
        run: flutter create . --org com.example --project-name zajel_app --platforms=android
      - name: Force Fix Android Configuration
        run: |
          BUILD_FILE="android/app/build.gradle"
          if [ -f "$BUILD_FILE" ]; then
            sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 23/g' "$BUILD_FILE"
            sed -i 's/minSdk = flutter.minSdkVersion/minSdk = 23/g' "$BUILD_FILE"
          fi
          
          # التأكد من دعم كوتلن بشكل حديث وسليم
          PROP_FILE="android/gradle.properties"
          if [ -f "$PROP_FILE" ]; then
            echo "android.useAndroidX=true" >> "$PROP_FILE"
            echo "android.enableJetifier=true" >> "$PROP_FILE"
          fi
      - run: flutter pub get
      - run: flutter build apk --release --no-shrink --no-tree-shake-icons
